### PR TITLE
Added video classification using ViViT model (Unit-7 notebook)

### PR DESCRIPTION
**Pull request by DiwakarBasnet**
Added colab notebook for implementation of fine-tuning ViViT model for video classification task.

### CODE REVIEW

**Comment by johko** [comment]
Hey @DiwakarBasnet, thanks for contributing this notebook. I just ran the code in colab and it all worked, which is amazing :wink: 
I'll go through the text in the next days, because I think there are a few grammatical things that can be improved, but great work already :+1:

**Review by sergiopaniego — COMMENTED** [review]
Thanks @DiwakarBasnet 😄!
I'll conduct an in-depth review but you can already review the general text since there are some small issues like:

* `architecuter` in the second paragraph

**Comment by DiwakarBasnet** [comment]
Hey @johko, thanks so much for your feedback! I'm glad to hear that the code worked well for you in Colab, that's awesome to know! 😄
The notebook was actually done quite a while ago, so it could definitely use some updates. I had intended to make the PR sooner, but I got caught up with other tasks. I’m glad to finally get this out there, and I’m looking forward to your suggestions on how we can improve it. Thanks again for your help! 👍

**Review by sergiopaniego — COMMENTED** [review]
Made some comments on the notebook 😄

**Comment by DiwakarBasnet** [comment]
I have updated the notebook with the comments you have made @sergiopaniego 😊. If there is a better way to show the videos in the notebook do let me know 🤗

**Review by sergiopaniego — COMMENTED** [review]
Thanks!

We may need to add the notebook to the table of contents 😄. https://huggingface.co/learn/computer-vision-course/unit0/welcome/TableOfContents

**Review by johko — APPROVED** [review]
Hey, sorry for the very very late reply and review. I had a rather quick run-through of the notebook just now and everything looks okay from my side

**Comment by johko** [comment]
@sergiopaniego as you reviewed this quite a bit - do you think this is approval worthy from your side?

**Comment by sergiopaniego** [comment]
Changes approved!
I think this notebook should be linked to the table of contents [here](https://huggingface.co/learn/computer-vision-course/unit0/welcome/TableOfContents) so it's visible. 
cc @DiwakarBasnet

**Comment by johko** [comment]
I agree with @sergiopaniego, when you added the notebook to the overview, we can merge this @DiwakarBasnet

**Comment by DiwakarBasnet** [comment]
Sorry couldn't see the comments, I have linked the notebook to Table of contents

**Pull request merged**
