### PR TITLE
Remove the redundant line of code

### PR DESCRIPTION
**Pull request by mohammad-gh009**
self.b1 = BaseConv2d(in_channels, n1x1, kernel_size=1)

this line of code was redundant in the GoogleNet architecture.

### CODE REVIEW

**Review by mmhamdy — APPROVED** [review]
Nice catch! Thanks

**Review by bellabf — APPROVED** [review]
Thank you

**Comment by merveenoyan** [comment]
@mohammad-gh009 can you resolve merge conflicts? resnet PR has changed the file a bit

**Comment by mohammad-gh009** [comment]
@merveenoyan I resolved the merge conflict.

**Comment by merveenoyan** [comment]
@mohammad-gh009 you need to pull this and run the code_formatter.py script

**Comment by mohammad-gh009** [comment]
Done !

**Comment by mohammad-gh009** [comment]
@merveenoyan hey merve, can you review this code?

**Review by johko — APPROVED** [review]
good to go :+1:

**Pull request merged**
