### PR TITLE
Requirements for the Computer Vision Course

### PR DESCRIPTION
**Pull request by notvicent3**
I think these are the fundamental dependencies.

### CODE REVIEW

**Review by johko — APPROVED** [review]
LGTM :+1:  and nice that you even thought of dependabot :smile:

**Comment by notvicent3** [comment]
Added readme.md and solved some issues with the security of pillow scipy and transformers versions

**Comment by notvicent3** [comment]
So atm I think is enough dependencies atm. In the future we can adapt while the content evolves.

**Comment by notvicent3** [comment]
My god, github, sorry.

**Pull request merged**
