### PR TITLE
Fix links to images and update welcome.mdx

### PR DESCRIPTION
**Pull request by kfahn22**
I realized when I looked the dev version of course that I hadn't linked properly to the images (hopefully fixed now).  I also noticed that I am listed 2x in ch.1 and as a reviewer in ch. 10.  I have fixed that.

I also updated the link in point_clouds.mdx and removed a hanging title.

(I also ran  the code_formatter.py script just in case.)

### CODE REVIEW

**Review by MKhalusova — APPROVED** [review]
LGTM, thanks!

**Comment by kfahn22** [comment]
@MKhalusova I just realized that my images are not a standard size. Is there a standard image format for the HF website (image width?).  What about YouTube links?

**Comment by kfahn22** [comment]
@MKhalusova I have updated the links for the files that on the units that I worked on (feature-extraction and synthetic-data-creation.  I just did a search and there are other files with the same issue (blob instead of resolve).   I can update those, but would that make this pull request too big?

**Review by merveenoyan — APPROVED** [review]
great @kfahn22 thank you!!!

**Pull request merged**
