### PR TITLE
add reviewer instructions

### PR DESCRIPTION
**Pull request by johko**
I added some instructions how people can sign up to become reviewers. Let me know what you think :)

### CODE REVIEW

**Review by chiho-5 — APPROVED** [review]
I think it's nice. If we're left to review everything then the review process will be slow. . So it's best 
I also think that the reviewer should be guided on writing mechanics (so as to correct grammar errors) and if possible run some codes to make sure it works as is.

**Comment by lunarflu** [comment]
Overall it looks great! Thanks for putting it together. I added some adjustments aimed at making them flow smoother from one point to the next, and emphasizing a bit harder our ambitions, some grammar stuff etc. (Let me know what you think about the way I've done it, seemed faster to adjust -> directly commit, but maybe there are better ways)

**Review by lunarflu — APPROVED** [review]
Broadly looks good to me!

**Review by chiho-5 — APPROVED** [review]
It looks much better now

**Pull request merged**
