### PR TITLE
Fix doc-builder

### PR DESCRIPTION
**Pull request by mishig25**
Fixes the toctree.

You can check how the course is looking by going to: https://moon-ci-docs.huggingface.co/docs/computer-vision-course/pr_212/en/Unit%200%20-%20Welcome/welcome

image

### CODE REVIEW

**Review by merveenoyan — APPROVED** [review]
Thanks a lot Mishig, you're the best!

**Comment by mishig25** [comment]
What should I do for the failing "Quality check"?

**Comment by mishig25** [comment]
You can check how the course is looking by going to: https://moon-ci-docs.huggingface.co/docs/computer-vision-course/pr_212/en/Unit%200%20-%20Welcome/welcome

image

**Comment by merveenoyan** [comment]
@mishig25 you can run make quality if possible

**Review by ratan — APPROVED** [review]

**Pull request merged**
