### PR TITLE
(not final) Adding chapters

### PR DESCRIPTION
**Pull request by lunarflu**
Obviously subject to change - Any ideas / preferences for preferred formats to write in (.mdx etc?)

### CODE REVIEW

**Comment by notvicent3** [comment]
I wanted to review the content you've created in the PR, but I think it's smarter to wait to see "what is defined" as "content".

**Comment by johko** [comment]
Thanks for the PR @lunarflu, but I would also say with a lot of new people and the current development in the discord channel, we should wait a bit before adding the chapters here

**Comment by lunarflu** [comment]
> Thanks for the PR @lunarflu, but I would also say with a lot of new people and the current development in the discord channel, we should wait a bit before adding the chapters here

SGTM 🤗

**Comment by johko** [comment]
I've created an update PR for the chapters here: #11.  So will close this one.

**Pull request closed without merging**
