### PR TITLE
unit 8 fixes - latex stuff and broken link minor corrections

### PR DESCRIPTION
**Pull request by psetinek**
Some fixes for chapter 8:
- mainly latex related where I changed $...$ to \\( ... \\).
- fixed Rotation matrix around z-axis in the linear algebra mdx.
- fixed path to image for NeRF encodings in nerf mdx.

### CODE REVIEW

**Review by bellabf — APPROVED** [review]
Thank you!

For some housekeeping, the z-axis rotation fixes the issue https://github.com/johko/computer-vision-course/issues/283

**Comment by sergiopaniego** [comment]
Could it be better if there was a space between the Latex text and the rest? 
Like in here:

image

Reference: https://moon-ci-docs.huggingface.co/docs/computer-vision-course/pr_285/unit8/3d-vision/nvs

**Comment by bellabf** [comment]
> Could it be better if there was a space between the Latex text and the rest? Like in here:
> 
> image
> 
> Reference: https://moon-ci-docs.huggingface.co/docs/computer-vision-course/pr_285/unit8/3d-vision/nvs

I actually do not really know how to fix this. There is a similar problem with image.mdx in unit 1. I found digging some other PR that it was mentioned  https://github.com/johko/computer-vision-course/pull/228#issuecomment-2006591074 that the problem was from the docbuilder. Since multiple units have this problem, it would be better to fix the docbuilder. 

Maybe @merveenoyan  or @johko know more about this?

**Comment by merveenoyan** [comment]
@bellabf unfortunately this is an error on docbuilder's side

**Review by merveenoyan — APPROVED** [review]

**Comment by merveenoyan** [comment]
@psetinek would you be down to maybe write HTML to center images and the text underneath?

**Pull request merged**
