### PR TITLE
RE PR knowledge distillation

### PR DESCRIPTION
**Pull request by ghassen-fatnassi**
we already discussed the changes , this is just because of the merge conflict

### CODE REVIEW

**Comment by ghassen-fatnassi** [comment]
@mmhamdy @johko

**Review by mmhamdy — APPROVED** [review]
Nice job! Thanks! 😀

**Comment by ghassen-fatnassi** [comment]
same problem as before : [issue link](https://github.com/johko/computer-vision-course/actions/runs/11166622771?notification_referrer_id=NT_kwDOCGcbuLUxMjcwMjM0MTkzNDoxNDA5NzUwMzI)

**Review by johko — APPROVED** [review]
Thanks for taking care of it :pray:  and sorry for the extra work of creating a new PR

**Comment by johko** [comment]
> same problem as before : [issue link](https://github.com/johko/computer-vision-course/actions/runs/11166622771?notification_referrer_id=NT_kwDOCGcbuLUxMjcwMjM0MTkzNDoxNDA5NzUwMzI)

Yeah, sorry about that. The error has been existing for a while and I'm trying my best to fix it, but I think it is related to an access token I cannot generate, but only people from the HF core team. I wasn't really successful in getting an answer from anyone yet though. But I will merge the PR anyway and as soon as the error is fixed, it will show in the course on the website.

**Comment by ghassen-fatnassi** [comment]
thanks a lot man , I'm really motivated to share any knwoledge i acquire in the future <3
thanks for your time !

**Pull request merged**
