### PR TITLE
Format files and fix issues found by quality check

### PR DESCRIPTION
**Pull request by kfahn22**
Only change is replacing single quotes with ""

### CODE REVIEW

**Comment by kfahn22** [comment]
@MKhalusova  I would not be surprised about that.  How do I check locally?  I have used npm to run tests on json files, but I am not sure how to check the mdx files.

**Comment by MKhalusova** [comment]
Run `python utils/code_formatter.py` locally (without the `--check_only` flag), it should fix all the issues

**Comment by kfahn22** [comment]
Thanks! I was trying to pass the computer-vision-course  folder as an argument.

**Comment by kfahn22** [comment]
@MKhalusova I have added the fixes for the first two mdx files that were failed the checks.  Feature-matchng.mdx is still failing with the change to  "".

**Comment by kfahn22** [comment]
@MKhalusova Yea, It passed the quality checks!

**Comment by MKhalusova** [comment]
Hooray! :tada:

**Review by lunarflu — APPROVED** [review]
LGTM, thanks @kfahn22 ! 🤗

**Comment by MKhalusova** [comment]
> just one thing here I think
> `Error: Process completed with exit code 1.`

If you're referring to the build_pr_documentation job, I don't think it's working yet.

**Review by merveenoyan — APPROVED** [review]
Thank you!

**Pull request merged**
