### PR TITLE
Unit 10 - Synthetic Data Creation -- add notebook

### PR DESCRIPTION
**Pull request by kfahn22**
This pull request adds a notebook to demo how to use the stablityai/sdxl-turbo model to generate a synthetic dataset for artistic purposes and push to the hub.  I have pushed the dataset to my own name, but could change to hf-vision repo.

### CODE REVIEW

**Review by merveenoyan — COMMENTED** [review]
Very useful section and cool ideas (I really like your PRs honestly 🫡) Only left nits otherwise LGTM

**Comment by kfahn22** [comment]
<p>Thanks, I wasn't sure.  </p>

---

 <a href='https://app.reviewnb.com/johko/computer-vision-course/pull/167/discussion/#comment-1875663971'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by kfahn22** [comment]
@merveenoyan  Thanks for the feedback!

 I changed the headers to 3.  Please let me know if I need to make any other changes.

**Review by merveenoyan — APPROVED** [review]
Thank you!

**Review by johko — APPROVED** [review]
Useful and simple, very nice :+1: 

Just left one small comment ;)

**Pull request merged**
