### PR TITLE
Test mathjax delimiter

### PR DESCRIPTION
**Pull request by klyap**

### CODE REVIEW

**Comment by klyap** [comment]
Whoops opened PR on wrong repo

**Comment by sarthak247** [comment]
Hey, I just wanted to ask where you able to get it working? I tried looking it up and it shows that I need to add some extra plugins for it to be able to render properly in .mdx but I couldn't figure it out. *sigh*

**Comment by klyap** [comment]
@sarthak247 I wasn't able to! I think there's a response on https://github.com/johko/computer-vision-course/issues/77#issuecomment-1847628590 

Seems like doc-builder is the way to go?

**Comment by sarthak247** [comment]
I also wasn't able to figure it out and for docbuilder to work I guess the toctree needs to be complete first. I'll give it a try and let you know how it goes and will even add a screenshot of the rendered document if it works. Cheers :v:

**Pull request closed without merging**
