### PR TITLE
Update welcome.mdx

### PR DESCRIPTION
**Pull request by ghassen-fatnassi**
added myself :)

### CODE REVIEW

**Review by sergiopaniego — COMMENTED** [review]
Thanks @ghassen-fatnassi! We discussed on Discord about making `stage` branch the default so I guess this addition can already target it 😄

**Comment by ghassen-fatnassi** [comment]
> Thanks @ghassen-fatnassi! We discussed on Discord about making `stage` branch the default so I guess this addition can already target it 😄

this is my first time creating a pull request and i'm not very familiar what you just said :) can you please clarify , thanks!

**Comment by sergiopaniego** [comment]
> > Thanks @ghassen-fatnassi! We discussed on Discord about making `stage` branch the default so I guess this addition can already target it 😄
> 
> this is my first time creating a pull request and i'm not very familiar what you just said :) can you please clarify , thanks!

Sure!
You've created a PR from your forked repo that will be merged into the `main` branch of this repo. We talked on [Discord](https://github.com/johko/computer-vision-course?tab=readme-ov-file#hugging-face-computer-vision-community) about making the `stage` branch of this repo the default one, so any new PR should be merged into that branch instead of the `main`. 


You can see this info in the upper part of this page:

image

To change the target branch, you can press the `Edit` button on the top-right and select the target branch (where it says `main`, it should be `stage`):

image

**Comment by ghassen-fatnassi** [comment]
> > > Thanks @ghassen-fatnassi! We discussed on Discord about making `stage` branch the default so I guess this addition can already target it 😄
> > 
> > 
> > this is my first time creating a pull request and i'm not very familiar what you just said :) can you please clarify , thanks!
> 
> Sure! You've created a PR from your forked repo that will be merged into the `main` branch of this repo. We talked on [Discord](https://github.com/johko/computer-vision-course?tab=readme-ov-file#hugging-face-computer-vision-community) about making the `stage` branch of this repo the default one, so any new PR should be merged into that branch instead of the `main`.
> 
> You can see this info in the upper part of this page:
> 
> image
> To change the target branch, you can press the `Edit` button on the top-right and select the target branch (where it says `main`, it should be `stage`):
> 
> image

done , thanks a lot

**Comment by johko** [comment]
Hey @ghassen-fatnassi , sorry for the confusion with the branches and thanks for changing to the staging branch. Now it shows some conflicting files, because probably your branch is not completely up-to-date with our stage branch.

I'm also not a git expert but I think you can try to run `git rebase upstream/stage` in a terminal when inside your project folder and should be able to resolve the conflicts locally. Then commit and push the result
If you have more questions or problems with that, let me know :)

**Pull request closed without merging**
