### PR TITLE
Unit-3 Chapter-3 Vision Transformers Image Classification with LoRA 

### PR DESCRIPTION
**Pull request by alanahmet**
Hey everyone,

This is draft for the LoRA Image Classification notebook. I would appreciate any feedback!

### CODE REVIEW

**Review by ricard-inho — COMMENTED** [review]
I added some formatting comments on the Image classification using LoRA with Vision Transformers. I think overall is easy to follow and understand LoRA concepts!

**Review by merveenoyan — COMMENTED** [review]
I've mostly done nit-picking, the notebooks are very explanatory it's pretty ready to merge once the comments are addressed. Thanks a lot for this amazing work!

**Comment by merveenoyan** [comment]
@alanahmet I realized I left comments on image classification one as well, sorry for confusion, feel free to ignore them 😊

**Comment by alanahmet** [comment]
<p>Hi Merve, thanks for the great suggestions :) </p><p>I couldn't find the Metric tab on hub for peft model, should I also download the main model to the hub to see metrics?</p>

---

 <a href='https://app.reviewnb.com/johko/computer-vision-course/pull/108/discussion/#comment-1850209836'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by merveenoyan** [comment]
<p>Ah no, you mean tensorboard? </p>

---

 <a href='https://app.reviewnb.com/johko/computer-vision-course/pull/108/discussion/#comment-1850209836'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by alanahmet** [comment]
<p>Am I mistaken or do you mean a tensorboard similar to the one shown on this page? <a href="https://huggingface.co/docs/hub/tensorboard" target="_blank">https://huggingface.co/docs/hub/tensorboard</a></p><p>If its the case I couldn't find metric tab on trained peft model(<a href="https://huggingface.co/alanahmet/vit-base-patch16-224-finetuned-lora-oxfordPets" target="_blank">https://huggingface.co/alanahmet/vit-base-patch16-224-finetuned-lora-oxfordPets</a>)</p>

---

 <a href='https://app.reviewnb.com/johko/computer-vision-course/pull/108/discussion/#comment-1850209836'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by merveenoyan** [comment]
<p>interesting, you can ignore this for now, I'll check since it seems like a bug</p>

---

 <a href='https://app.reviewnb.com/johko/computer-vision-course/pull/108/discussion/#comment-1850209836'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Review by merveenoyan — APPROVED** [review]
Looks good to me!
One last thing: can you sync the changes on vision transformers from either upstream (i.e. the repo you've forked from) or main (if the changes from that repository were merged) so we make sure there's no problem?

**Review by ATaylorAerospace — APPROVED** [review]
The remote-tracking branch 'upstream/main' was merged into LoRA-image-classification so this PR is good to go! Great work @alanahmet

**Review by ricard-inho — APPROVED** [review]

**Pull request merged**
