### PR TITLE
Latest rendering fixes (unit 8 - introduction to stereo vision)

### PR DESCRIPTION
**Pull request by vasugupta9**
Update
Rendering fixes are done. PR is ready for review !

Previous
Some latex rendering fixes. Few more to follow. Will update here once all fixes are made !

### CODE REVIEW

**Review by merveenoyan — APPROVED** [review]
Thanks a lot!

**Comment by merveenoyan** [comment]
@vasugupta9 your PR is rendered here  https://moon-ci-docs.huggingface.co/docs/computer-vision-course/pr_241/en/Unit%200%20-%20Welcome/welcome

**Comment by vasugupta9** [comment]
thanks @merveenoyan !

**Review by MKhalusova — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
