### PR TITLE
Update feature-matching.mdx(typo)

### PR DESCRIPTION
**Pull request by mohammad-gh009**

### CODE REVIEW

**Review by mmhamdy — APPROVED** [review]
Thanks

**Comment by omkar-12bits** [comment]
#267 deal with this issue on broader aspect

**Review by mmhamdy — COMMENTED** [review]
Yup! looks like @omkar-12bits already has taken care of this more broadly in a previous PR.

**Comment by bellabf** [comment]
> Yup! looks like @omkar-12bits already has taken care of this more broadly in a previous PR.

Ops, I should have noticed that. Maybe we can close this PR.

**Comment by mmhamdy** [comment]
Hi @mohammad-gh009, your changes are already addressed here #267. If you don't have any other additions, I think we may close this PR.

**Comment by mohammad-gh009** [comment]
OK!

**Pull request closed without merging**
