### PR TITLE
Fixing error in transfer learning notebook

### LINKED ISSUE #311: Unit 3 - Vision Transformer: Transfer learning notebook dataset loads without decoding the images.
The [notebook](https://github.com/johko/computer-vision-course/blob/main/notebooks/Unit%203%20-%20Vision%20Transformers/transfer-learning-image-classification.ipynb) expects a PIL image under each data point's `'image'` key, but it actually loads a dict with `'path'` and `'bytes'` (the dataset is not decoded). This makes the notebook fail, starting from the cell in which some images are displayed.

Not sure this is the right solution but, by explicitly doing the decoding when loading the dataset solves it:

```python
dataset = load_dataset('pcuenq/oxford-pets').cast_column('image', Image(decode=True))
```

(importing `Image` from `datasets`).

### LINKED ISSUE #312: transfer-learning-image-classification.ipynb error
I'm getting an error when running this Colab notebook. When I run the cell dataset['train'][0], the 'image' field is a long list of bytes. I think this is the cause of the following error that I get when I run the succeeding cell: 'TypeError: Image data of dtype object cannot be converted to float'. Any suggestions?

### LINKED ISSUE #322: LoRA-Image-Classification Notebook , dataset type is different while downloading
In the LoRA-Image-Classification Notebook from the course when running on Google Colab after importing the dataset using
`dataset = load_dataset('pcuenq/oxford-pets')`
The dataset structure is 
`{'path': '/data/datasets/magic-ml/oxford-iiit-pet/images/Siamese_137.jpg',
 'label': 'Siamese',
 'dog': False,
 'image': {'bytes': b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x01\x01\x00\x00\x01\x00\x01\x00\x00\xff\xdb\x00C\x00\x08\x06\x06\x07\x06\x05\x08\x07\x07\x07\t\t\x08\n\x0c\x14\r\x0c\x0b\x0b\x0c\x19\x12\x13\x0f\x14\x1d\x1a\x1f\x1e\x1d\x1a\x1c\x1c $.\' ",#\x1c\x1c(7),0`
I think the data is not in PIL format while the code in Notebook expects in PIL format at different places 
for example here
`def show_samples(ds,rows=2,cols=4):
    samples = ds.shuffle().select(np.arange(rows*cols))
    fig = plt.figure(figsize=(cols*4,rows*4))
    for i in range(rows*cols):
        img = samples[i]['image']`
and 
`from PIL import Image
def transforms(batch):
    batch['image'] = [x.convert('RGB') for x in batch['image']]
    inputs = processor([x for x in batch['image']],return_tensors='pt')
    inputs['labels']=[label2id[y] for y in batch['label']]
    return inputs
dataset = dataset.with_transform(transforms)`

I solved it using 
`def transforms(batch):
    # Convert bytes to PIL images
    batch['image'] = [Image.open(BytesIO(x['bytes'])).convert('RGB') for x in batch['image']]  
    inputs = processor([x for x in batch['image']],return_tensors='pt')
    inputs['labels']=[label2id[y] for y in batch['label']]
    return inputs`

I dont know whether other people get similar error or not in Google colab

### PR DESCRIPTION
**Pull request by kawchar85**
### Fixes Image Bytes Handling in Dataset Processing
The dataset feature 'image' is not a processed image but actually contains raw byte data.
Updated the code to handle the byte data correctly by replacing (in `show_samples` and `show_predictions` function) :
```python
img = samples[i]['image']
```
with:
```python
img_bytes = samples[i]['image']['bytes']
img = Image.open(io.BytesIO(img_bytes))
```
And in the `transforms` function, replaceing the line:
```python
batch['image'] = [x.convert('RGB') for x in batch['image']]
```
with:
```python
batch['image'] = [Image.open(io.BytesIO(x['bytes'])).convert('RGB') for x in batch['image']]
```

#### Related Issue:
Fixes #311 , Fixes #312 , Fixes #322

### CODE REVIEW

**Review by johko — CHANGES_REQUESTED** [review]
Thanks for the fixes @kawchar85 , absolutely makes sense.
I just left two comments, basically removing the two lines that are not needed anymore, apart from that it looks good :)

**Comment by kawchar85** [comment]
@johko  Thank you for the feedback! I've removed the commented-out lines as suggested. Please review the updated changes.

**Comment by johko** [comment]
Thanks for the changes @kawchar85. There is one security issue I just spotted (see comment above), would be great if you can clear that and then the PR is ready to merge from my side :)

**Review by johko — APPROVED** [review]
Thanks, LGTM :+1:

**Comment by kawchar85** [comment]
@johko  Thank you for pointing out the exposed token. I’ve removed it from the code and updated the pull request. Please let me know if there are any further issues.

**Review by ATaylorAerospace — APPROVED** [review]
Thanks for catching this error. LGTM

**Comment by kawchar85** [comment]
@ATaylorAerospace Thank you for reviewing and approving the pull request! I’m glad the fix addresses the issue. If there are any further comments or if I can help with anything else, please let me know.

**Pull request merged**
