### PR TITLE
Supplementary resources Unit 12: Ethics and Bias

### PR DESCRIPTION
**Pull request by snehilsanyal**
Hey everyone 🤗 
Just added a quick section on supplementary resources for Unit 12: Ethics and Bias in CV. It contains a few resources that learners can go through after they complete the unit. Inspired by: [HF audio course](https://huggingface.co/learn/audio-course/chapter5/supplemental_reading). Open for suggestions 😄 
**Related to Issue:** #51 

Best,
Ethics and Bias Team.
cc: @BettyFabre, @Zekrom-7780 @miniMaddy

### CODE REVIEW

**Comment by charchit7** [comment]
Looks nice, you can also this recent course from MIT: https://ocw.mit.edu/courses/res-10-002-ethics-of-ai-bias-spring-2023/

**Review by ATaylorAerospace — APPROVED** [review]
@snehilsanyal This is a great list of addditional resources.

**Comment by snehilsanyal** [comment]
> Looks nice, you can also this recent course from MIT: https://ocw.mit.edu/courses/res-10-002-ethics-of-ai-bias-spring-2023/

Thank you @charchit7 glad you liked it, surely I will add this in the list 😄

**Review by Zekrom-7780 — APPROVED** [review]

**Review by charchit7 — APPROVED** [review]

**Review by merveenoyan — APPROVED** [review]
Thanks!

**Pull request merged**
