### PR TITLE
Unit 4. Multimodal models transfer learning. CLIP transfer learning notebook

### PR DESCRIPTION
**Pull request by minemile**
Hi all!

We have prepared a CLIP transfer learning notebook. In this notebook we review various fine-tuning techniques for the classification task on Oxford-pet dataset.

I will be glad to any feedback!

### CODE REVIEW

**Review by merveenoyan — COMMENTED** [review]
I left mostly nitpicks on wording, very informative notebook. Thank you!

**Review by MKhalusova — APPROVED** [review]
Excellent work! Not much to add to @merveenoyan 's comments.

**Review by ratan — APPROVED** [review]

**Comment by minemile** [comment]
<p>Fixed</p>

---

 <a href='https://app.reviewnb.com/johko/computer-vision-course/pull/176/discussion/#comment-1886959015'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by minemile** [comment]
<p>Fixed</p>

---

 <a href='https://app.reviewnb.com/johko/computer-vision-course/pull/176/discussion/#comment-1892612814'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by minemile** [comment]
<p>Fixed</p>

---

 <a href='https://app.reviewnb.com/johko/computer-vision-course/pull/176/discussion/#comment-1886958933'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by minemile** [comment]
<p>Fixed</p>

---

 <a href='https://app.reviewnb.com/johko/computer-vision-course/pull/176/discussion/#comment-1886958951'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Review by merveenoyan — APPROVED** [review]
LGTM

**Pull request merged**
