### PR TITLE
Updates  links to images and fixes a link to a Gradio space that was getting a 404

### PR DESCRIPTION
**Pull request by kfahn22**
Updates links to images:
chapters/en/Unit 4 - Multimodal Models/CLIP and relatives/Introduction.mdx
chapters/en/Unit 4 - Multimodal Models/CLIP and relatives/losses.mdx
chapters/en/Unit 6 - Basic CV Tasks/segmentation.mdx
chapters/en/Unit 8 - 3D Vision, Scene Rendering and Reconstruction/nerf.mdx
chapters/en/Unit 9 - Model Optimization/intro_to_model_optimization.mdx
chapters/en/Unit 12 - Ethics and Biases/ethics-bias-ai.mdx

Update link to Gradio space:
chapters/en/Unit 4 - Multimodal Models/CLIP and relatives/blip.mdx

### CODE REVIEW

**Comment by kfahn22** [comment]
In updating the image links, I noticed that the LateX is formatted properly in line 18 of chapters/en/Unit 4 - Multimodal Models/CLIP and relatives/losses.mdx, but not within text of next paragraph.  I tried changing  $...$ to $$...$$ but that didn't fix it.  

Another TODO: links to notebooks need to be fixed

**Review by MKhalusova — COMMENTED** [review]
The images fix looks good to me, where exactly is the issue with latex? `$$` should work.

**Comment by kfahn22** [comment]
This is what is looks like:
Screenshot 2024-02-29 at 1 30 34 PM

**Comment by MKhalusova** [comment]
@kfahn22 This is odd. I'm not sure exactly why this happens, but one guess that I have is that list formatting might be messing with it. As an experiment, can you make it a paragraph instead of a bulleted list to see if this will help?

**Comment by kfahn22** [comment]
It didn't fix it.
Screenshot 2024-02-29 at 1 52 34 PM

**Comment by MKhalusova** [comment]
@kfahn22 I think I found the issue - https://github.com/huggingface/doc-builder#latex
The inline latex is expected to be in the following format: ` \\( ... )\\`

**Comment by kfahn22** [comment]
@MKhalusova The LateX is rendering, but the spacing is a little off (I noticed the same thing on the reference page, though).  
Screenshot 2024-02-29 at 5 37 03 PM

**Comment by kfahn22** [comment]
I have experimenting with adding spaces, but that has not been productive.  Ironically, in a couple of tries, the spacing for some of the inline Latex has been OK (but never all of them), and I can't figure out why.  

I also just realized in looking through the mdx files (looking to see if there was an example of inline LateX without the spec ing issue) that there are additional mdx files with image links that need to be updated.  They aren't in the course assets folder--dooes not matter?

**Comment by merveenoyan** [comment]
pinging @mishig25 here he likely knows

**Comment by merveenoyan** [comment]
@kfahn22 in BLIP demo you can replace hysts with merve and it will work, I forked that demo and fixed previously

**Comment by kfahn22** [comment]
@merveenoyan I updated the link from "https://hysts-BLIP2-with-transformers.hf.space"  to "https://hysts-BLIP2.hf.space" and I just checked and it is working.  Should I still update?

**Comment by merveenoyan** [comment]
@kfahn22 BTW I'm fixing inline LaTeX rn let's see

**Comment by kfahn22** [comment]
@merveenoyan

FYI, I tried the notebook link in chapters/en/Unit 9 - Model Optimization/tools_and_frameworks.mdx and got Access Denied message. (And the links to notebooks in mdx files I added won't work.)

Also, I  just noticed that the one of the images in chapters/en/Unit 13 - Outlook/hyena.mdx isn't in the course-assets repo.  (toeplitz_conv.jpg)

**Comment by kfahn22** [comment]
@merveenoyan  I am closing this PR since it looks like #224 addresses almost all of the same issues, except: 
chapters/en/Unit 8 - 3D Vision, Scene Rendering and Reconstruction/nerf.mdx
chapters/en/Unit 9 - Model Optimization/intro_to_model_optimization.mdx

**Pull request closed without merging**
