### PR TITLE
typo in import statement

### PR DESCRIPTION
**Pull request by omkar-12bits**
imported as cv2 but used as cv in code snippets. fixed with alias cv instead of making changes everywhere with cv -> cv2.

### CODE REVIEW

**Comment by merveenoyan** [comment]
I think instead of aliasing if you could change cv's to cv2 it would be better :)

**Review by bellabf — APPROVED** [review]

**Comment by omkar-12bits** [comment]
Ok , done.

**Comment by omkar-12bits** [comment]
i can't preview this mdx file because of this error of not having `/>` in the end of the img tag in line 62.
is it ok to let it as it is or should i change it to 
```<div class="flex justify-center">
    <img src="https://huggingface.co/datasets/hf-vision/course-assets/resolve/main/feature-extraction-feature-matching/SIFT.png" alt="SIFT">
</div>```

```<div class="flex justify-center">
    <img src="https://huggingface.co/datasets/hf-vision/course-assets/resolve/main/feature-extraction-feature-matching/SIFT.png" alt="SIFT"/>```
</div>

**Review by mmhamdy — APPROVED** [review]
Nice! Thanks

**Review by merveenoyan — APPROVED** [review]
thanks!

**Pull request merged**
