### PR TITLE
fix link to discord

### PR DESCRIPTION
**Pull request by matthewbcool**
The vanity link is broken so I created a new one to fix.

### CODE REVIEW

**Review by merveenoyan — APPROVED** [review]
Thank you!

**Comment by merveenoyan** [comment]
For me the link works @matthewbcool, can't reproduce the problem

**Comment by matthewbcool** [comment]
> For me the link works @matthewbcool, can't reproduce the problem

I think its because the server is no longer level 3 (supports custom invite links). I would imagine the link still works if you are already a member.

**Comment by johko** [comment]
> I think its because the server is no longer level 3 (supports custom invite links). I would imagine the link still works if you are already a member.

Interesting, as I have no idea about discord links I trust the Mozilla Community Manager :laughing:

**Review by johko — APPROVED** [review]

**Pull request merged**
