### PR TITLE
Fix failing tests

### PR DESCRIPTION
**Pull request by mmhamdy**
Fix the failing tests:

- Fix the naming problem in `_toctree.yml`
- Create Makefile for quality checks.

### CODE REVIEW

**Review by ratan — APPROVED** [review]
LGTM

**Comment by kfahn22** [comment]
The quality check is stopping at Unit 3 - Vision Transformers/Convolutional Vision Transformer.mdx.  I believe the cause is an indenting issue in forward() within VisionTransformer().  (At least it is stopping at x = self.patch_embed(x).

**Comment by MKhalusova** [comment]
Can you also run the quality check and include updated files (e.g. currently the checks fail on some markdown files)

**Comment by kfahn22** [comment]
@mmhamdy Maybe you have already done this, but I updated chapters/en/Unit 3 - Vision Transformers/Convolutional Vision Transformer.mdx lines 227-247, with the following:  
```
        def forward(self, x):
           x = self.patch_embed(x)
           B, C, H, W = x.size()

           x = rearrange(x, 'b c h w -> b (h w) c')

           cls_tokens = None
           if self.cls_token is not None:
               cls_tokens = self.cls_token.expand(B, -1, -1)
               x = torch.cat((cls_tokens, x), dim=1)

           x = self.pos_drop(x)

           for i, blk in enumerate(self.blocks):
               x = blk(x, H, W)

           if self.cls_token is not None:
               cls_tokens, x = torch.split(x, [1, H*W], 1)
           x = rearrange(x, 'b (h w) c -> b c h w', h=H, w=W)

           return x, cls_tokens
```

Line 136 of chapters/en/Unit 3 - Vision Transformers/Swin Transformer.mdx has a typo:
```
            x = x + self.absolute_pos_embedclass SwinTransformer(nn.Module)
```
 Remove "class SwinTransformer(nn.Module)"

**Comment by kfahn22** [comment]
@MKhalusova  The next mdx file with an issue is one I added, feature-matching.mdx.  
The check stops at line 29.  I am assuming the issue is there is not a valid path to the image, but opencv-python isn't in the requirements.txt file yet.  Would that cause the check  to fail as well?

```
img1 = cv.imread('image1.png',cv.IMREAD_GRAYSCALE)
```

Will this pass the test?:
```
image1 = "path_to_image1"
img1 = cv.imread(image1,cv.IMREAD_GRAYSCALE)
```

**Comment by MKhalusova** [comment]
No, it's the single quote instead of `"`. It should be

`img1 = cv.imread("image1.png",cv.IMREAD_GRAYSCALE)`

**Comment by merveenoyan** [comment]
@mmhamdy the tests will fail until we add the token to the GHActions BTW which Johannes will do soon.

**Comment by kfahn22** [comment]
@mmhamdy I have added the fixes to #211 b/c I am trying to fix the mdx file I added and you have to address them sequentially.

**Comment by mmhamdy** [comment]
Hi guys, sorry for the late response
> Can you also run the quality check and include updated files (e.g. currently the checks fail on some markdown files)?

Yeah, sure @MKhalusova. I just didn't want this PR to be overwhelming.

> @mmhamdy I have added the the formatting changes to https://github.com/johko/computer-vision-course/pull/211 and thanks to you it now passes the quality checks.

That's great @kfahn22, I've essentially done nothing 😃 just added the formatting script.

> maybe we should add an instruction on the README as well on how to make sure the PRs are up to date with quality.

Yes, of course. That would be really helpful, @merveenoyan! Maybe a separate `CONTRIBUTING` file for easier reach. I'd be happy to work on it.

**Comment by johko** [comment]
Creating a `CONTRIBUTING` file sounds good @mmhamdy, feel free to draft one. I guess some info from the current README can also be included

**Comment by merveenoyan** [comment]
@mmhamdy I think @kfahn22's PR deriving from this PR has fixed many stuff https://github.com/johko/computer-vision-course/pull/211 if you have any other fix we can add them here and merge

**Pull request closed without merging**
